name: GitHub CI

on:
  push:
    branches: [ "releases/**" ]
  pull_request:
    branches: [ "releases/**" ]
    
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true
      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: echo ${{ steps.extract_branch.outputs.branch }} | cut -d "/" -f 2
      
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_branch.outputs.branch }} | cut -d "/" -f 2
          release_name: ${{ steps.extract_branch.outputs.branch }} | cut -d "/" -f 2