name: GitHub CI

on:
  push:
    branches: [ "test-release-gen" ]
  pull_request:
    branches: [ "test-release-gen" ]
    
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    env:
      VERSION: $(node -p "require('./package.json').version")

    steps:
      - uses: actions/checkout@v3
      - run: echo $VERSION
      - run: echo $GITHUB_VERSION
